### ISSUE TITLE
v4 theme looks different than the screenshot

### ISSUE THREAD

**Issue by steverandy** [wavebeem/vscode-theme-unoduetre#15]
Actual
<img width="1292" alt="Screenshot 2022-10-06 at 11 06 46 AM" src="https://user-images.githubusercontent.com/525332/194205028-a466f2d0-e358-4e8a-8728-f0a21729b3eb.png">

Expected
<img width="1392" alt="theme-light" src="https://user-images.githubusercontent.com/525332/194205169-a1cb6197-a677-4a16-9a6c-e7a9e37d88d7.png">

**Comment by wavebeem** [comment]
Yeah, I was a bit lazy about generating new screenshots. I'm gonna remove them and link to this site instead:

https://vscodethemes.com/e/wavebeem.theme-unoduetre/uno-due-tre?language=javascript

**Comment by wavebeem** [comment]
I've updated the README

If you prefer the old look, you can install an older version
