### ISSUE TITLE
Missing diff colors for .patch & .diff

### ISSUE THREAD

**Issue by svipas** [wavebeem/vscode-theme-unoduetre#17]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/10441177/234034749-59d2b638-507a-4879-8da3-b4b88f0f6092.png">

Colors are missing for diff (- +) for `.patch` and `.diff`

Code to test:

```patch
diff --git a/node_modules/apollo-cache-persist/CachePersistor.d.ts b/node_modules/apollo-cache-persist/CachePersistor.d.ts
index 503b59d..048434f 100644
--- a/node_modules/apollo-cache-persist/CachePersistor.d.ts
+++ b/node_modules/apollo-cache-persist/CachePersistor.d.ts
@@ -2,14 +2,13 @@ import Log from './Log';
 import Cache from './Cache';
 import Storage from './Storage';
 import Persistor from './Persistor';
-import Trigger from './Trigger';
 import { ApolloPersistOptions, LogLine } from './types';
 export default class CachePersistor<T> {
     log: Log<T>;
     cache: Cache<T>;
     storage: Storage<T>;
     persistor: Persistor<T>;
-    trigger: Trigger<T>;
+    trigger: never;
     constructor(options: ApolloPersistOptions<T>);
     persist(): Promise<void>;
     restore(): Promise<void>;
```

**Comment by wavebeem** [comment]
One of countless languages I've never tested... I'll try to remember when I have some free time. Thanks for the report.

Future note: These selectors should cover it:

```
meta.diff.header.git
meta.diff.header.from-file
meta.diff.header.to-file
meta.diff.range
punctuation.definition.deleted.diff
markup.deleted.diff
punctuation.definition.inserted.diff
markup.inserted.diff
```

**Comment by wavebeem** [comment]
![image](https://user-images.githubusercontent.com/176815/235327292-2bc3a9a8-e386-4b2e-b345-e717fa9a9925.png)

sadly, it doesn't look like you can choose background colors for text in vscode still :(

best i can do is just grab the three main theme colors and use those along with bold text and de-emphasizing the rest of the text.

**Comment by wavebeem** [comment]
hope that helps! i didn't change anything about the diff editor colors because that's a lot more involved.

**Comment by svipas** [comment]
Thanks a lot, I'm just not sure if `bold` was necessary 🤔

**Comment by wavebeem** [comment]
I'll think about it again next time I look at theme changes! I made it bold before I de-emphasized the non-diff text, and I found it especially important there.

**Comment by svipas** [comment]
Yeah do what works best, maybe now it looks a little bit odd to me, also it depends on font, some of them have really bold variants and different color is enough to show the difference.

BTW: Thanks a lot for the theme(s), they all look awesome and my favorite is Ocean! 😄

**Comment by wavebeem** [comment]
Glad you enjoy! My goal was to provide a type of theme that I felt like I hadn't seen yet, but I know _everyone_ has different favorite colors.

I feel like I may have actually made Ocean a little bit tougher to read recently... I've generally been using my new Miasma color a lot, though Ocean was my first theme with a colored background, so I have a lot of fond memories of it.

Feel free to give suggestions in the repo. I've definitely done some pretty big redesigns a few times, as my sensibilities have shifted over the years.
