### ISSUE TITLE
.swift colors aren't right

### ISSUE THREAD

**Issue by svipas** [wavebeem/vscode-theme-unoduetre#18]
Hey, seems like `.swift` uses wrong colors. I think it should use `D1DFFA` for some tokens (not all I guess?) instead of `5EBEED`. As an example you could take a look into Nord.

Uno Due Tre (Ocean):

<img width="479" alt="image" src="https://user-images.githubusercontent.com/10441177/235374461-f842cc95-1400-4fec-9215-bf5c495d4f62.png">

Nord:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/10441177/235374472-e8fce559-b46c-402f-85e7-6c20d232fbe4.png">

Code example:

```swift
import Foundation

extension Services {
    static var storeManagerService: StoreManagerServiceProtocol {
        StoreManagerService()
    }
}
```

**Comment by wavebeem** [comment]
oof, yeah there's definitely some kind of bug here. i think it might be an issue with nested contexts here, like maybe everything inside `extension Services` is getting "class" highlighting by default...

this might be a bit more involved, and i haven't seen this issue with JS/TS/Python so far (the languages i use most day-to-day)...

i've never done swift before, so it would be really helpful if you could share with me some kind of "test file" for swift that has a variety of syntax in it!

---

related: i've also been considering copying the syntax highlighting rules from the core vscode themes, but then just modifying the actual colors. if you've never seen it before, the colors are assigned via selectors similar to css, but i think it's just "first matching selector wins"

**Comment by svipas** [comment]
Uno Due Tre (Ocean):

<img width="529" alt="image" src="https://user-images.githubusercontent.com/10441177/235440665-8a59eb37-d57b-4de9-887e-c5d8fd6fbfb3.png">

Nord:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/10441177/235440695-0a039386-e142-40e1-bd96-d8640e18660e.png">

Default Dark:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/10441177/235440719-b85f4e69-b25b-41f2-a55d-86ada851fbc1.png">

Code example:

```swift
class Person {
    var name: String
    var age: Int
    
    init(name: String, age: Int) {
        self.name = name
        self.age = age
    }
    
    func sayHello() {
        print("Hello, my name is \(name) and I am \(age) years old.")
    }
}

enum Animal {
    case dog
    case cat
    case bird
}

extension Animal {
    func makeSound() -> String {
        switch self {
        case .dog:
            return "Woof!"
        case .cat:
            return "Meow!"
        case .bird:
            return "Tweet!"
        }
    }
}

let person = Person(name: "John", age: 25)
person.sayHello()

let animal = Animal.dog
print(animal.makeSound())
```

**Comment by wavebeem** [comment]
I just released v5.11.1 which should fix the issue :)

---

I've also released a hugely updated version of my Miasma sub-theme as a standalone theme with a lot of changes. Give it a try and let me know what you think (I know you prefer Ocean, though).

Maintaining 9 themes in one collection (including multiple light themes!) has been really tough, so I'm probably taking a break from this theme pack for a little while.

https://marketplace.visualstudio.com/items?itemName=wavebeem.miasma-vscode

**Comment by svipas** [comment]
@wavebeem Thanks a lot. Maybe you're thinking of splitting Ocean as well in some future? Because Miasma now looks really good, I was missing function call highlights and now it is there and it contains other changes like type colors. I'm going to use Miasma for now, maybe it will grow on me 😄

**Comment by wavebeem** [comment]
Yeah, I'm definitely thinking about what I want to do with this theme pack. I may come back and update it in the future, so don't lose hope. You can subscribe to GitHub updates for this repo if you wanna know. My partner uses `Uno Due Tre (Dark)` as her primary color scheme for years now, so I don't want to never update these themes again... I know there's a couple thousand people who've downloaded it 😮 

I _have_ done big breaking changes in the past on this theme pack, so maybe I'll copy what I've learned from the solo version of Miasma back here 😄  Time will tell 🤔
