### ISSUE TITLE
The color on text on tree is black, I can't read the text on file name.

### ISSUE THREAD

**Issue by davidcostadev** [wavebeem/vscode-theme-unoduetre#4]
First of all, I love this theme.
See differences on utils.js file

Print using your theme: 
![image](https://user-images.githubusercontent.com/3098556/57227029-cb91c500-6fe6-11e9-826f-3f0e1a99a887.png)

Print using virtual code default:
![image](https://user-images.githubusercontent.com/3098556/57227106-f5e38280-6fe6-11e9-906e-86fcc24a2298.png)

**Comment by wavebeem** [comment]
Oops! That was not an intentional color choice. I think I introduced a bug recently. I'll try to take a look soon.

**Comment by wavebeem** [comment]
v3.9.4 should resolve this issue. Let me know if you still see it after your extension updates.

**Comment by davidcostadev** [comment]
Oh! Now it's fix, thank you! I was so quickly! :-)

**Comment by wavebeem** [comment]
I use my own theme so it's in my best interest to fix bugs 😄  I had been meaning to fix this one for a while already.
