### ISSUE TITLE
Option for light background for status bar on light themes

### ISSUE THREAD

**Issue by steverandy** [wavebeem/vscode-theme-unoduetre#5]

**Comment by wavebeem** [comment]
Yeah I've gone back and forth on this. Some extensions were broken with a light color status bar but I'll probably bring it back. You can also add your own customizations on your vscode config to work around this

**Comment by wavebeem** [comment]
```
"workbench.colorCustomizations": {
// ... add colors here
}
```

https://code.visualstudio.com/api/references/theme-color#status-bar-colors

For now you can play with the status bar colors inside your config file like so^

I don't plan on adding a "mode" for this because it's already enough of a pain to keep all the themes in sync as is.

**Comment by wavebeem** [comment]
If you upgrade to 3.13.0 you'll see I went back to having a light status bar
